### ISSUE TITLE
error starting up

### ISSUE THREAD

**Issue by jots** [danielmai/.emacs.d#3]
On `GNU Emacs 24.4.1`

$ emacs -nw --debug-init
Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "s")

which is on line 185 of config.el:

```
(require 's)
(let* ((cmd "sw_vers -productVersion")
```

any idea what this is?  I think the idea of org mode for init files is _genius_.

**Comment by danielmai** [comment]
The line `(require 's)` loads the [s String library](magnars/s.el). The init didn't install the package beforehand so the error happens. An `M-x package install RET s` will fix that, but that definitely needs to be added to my config. Thanks!
