### ISSUE TITLE
Mac Customizations

### ISSUE THREAD

**Issue by therimalaya** [danielmai/.emacs.d#5]
I liked the customization with mac. I can play with cmd key. But with those customization enable, I am not able to use `{` and `}` keys and also `[` and `[` key. Is there any way to use the `cmd` keybinding along with getting those brackets.

**Comment by danielmai** [comment]
@therimalaya I'm not sure what the problem is here. In my set up, setting key bindings for "s-{" and "s-}" doesn't conflict with inserting "{", "}", "[", or "]". Are you still having this issue?

**Comment by danielmai** [comment]
I'll close this issue but let me know if it's still a problem.
